version: "3.3"
services:
  console:
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
    tty: true

  csv:
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
    tty: true

  test:
    build:
      dockerfile: ./.docker/test/Dockerfile
      context: .
    volumes:
      - .:/opt
