version: "3.3"
services:
  console:
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
    networks:
      - statistico-odds-checker_default
      - statistico_internal
    tty: true

  test:
    build:
      dockerfile: ./.docker/test/Dockerfile
      context: .
    volumes:
      - .:/opt

networks:
  statistico-odds-checker_default:
    external: false
  statistico_internal:
    external: true
