version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
  aws-ecs: circleci/aws-ecs@3.1.0

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:2023.10.1

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
#      - deploy:
#          context: aws
#          requires:
#            - build-and-test
#          filters:
#            branches:
#              only: master

jobs:
  build-and-test:
    working_directory: ~/go/src/github.com/statistico/statistico-odds-checker
    executor: machine-executor
    environment:
      GOPATH: /home/circleci/go
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: Build Release Image
          command: |
            make docker-build
      - run:
          name: Test Release Image
          command: |
            make test
      - run:
          name: Cache Built Images
          command: |
            chmod +x ./.circleci/deploy/docker-save.sh && ./.circleci/deploy/docker-save.sh
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - docker-cache

#  deploy:
#    executor: aws-cli/default
#    steps:
#      - checkout
#      - *attach_workspace
#      - aws-cli/setup
#      - run:
#          name: Deploy Artifacts to S3
#          command: aws s3 sync --exclude="*" --include="*.zip" /tmp/workspace/artifacts/ s3://statistico-lambda
#      - run:
#          name: Update Lambda Function
#          command: aws lambda update-function-code --function-name statistico-odds-checker --s3-bucket statistico-lambda --s3-key statistico-odds-checker.zip
