package betfair

var teams = map[string]string{
	"West Ham United": "West Ham",
	"Tottenham Hotspur": "Tottenham",
	"Liverpool": "Liverpool",
	"Manchester City": "Man City",
	"West Bromwich Albion": "West Brom",
	"Fulham": "Fulham",
	"Everton": "Everton",
	"Manchester United": "Man Utd",
	"Aston Villa": "Aston Villa",
	"Chelsea": "Chelsea",
	"Arsenal": "Arsenal",
	"Newcastle United": "Newcastle",
	"Sheffield United": "Sheff Utd",
	"Burnley": "Burnley",
	"Wolverhampton Wanders": "Wolves",
	"Roma": "Roma",
	"Leicester City": "Leicester",
	"Lazio": "Lazio",
	"Crystal Palace": "Crystal Palace",
	"Southampton": "Southampton",
	"Schalke 04": "Schalke",
	"Borussia Dortmund": "Dortmund",
	"Leeds United": "Leeds",
	"Brighton & Hove Albion": "Brighton",
	"Werder Bremen": "Werder Bremen",
	"Crotone": "Crotone",
	"Augsburg": "Augsburg",
	"Genoa": "Genoa",
	"Fiorentina": "Fiorentina",
	"Milan": "AC Milan",
	"RB Leipzig": "RB Leipzig",
	"Spezia": "Spezia",
	"Udinese": "Udinese",
	"Eintracht Frankfurt": "Eintracht Frankfurt",
	"Parma": "Parma",
	"Bayern München": "Bayern Munich",
	"Wolfsburg": "Wolfsburg",
	"Sampdoria": "Sampdoria",
	"Benevento": "Benevento",
	"Cagliari": "Cagliari",
	"Napoli": "Napoli",
	"Torino": "Torino",
	"Juventus": "Juventus",
	"Borussia M'gladbach": "Mgladbach",
	"Atalanta": "Atalanta",
	"Mainz 05": "Mainz",
	"Union Berlin": "Union Berlin",
	"Hellas Verona": "Verona",
	"Sassuolo": "Sassuolo",
	"Hoffenheim": "Hoffenheim",
	"Arminia Bielefeld": "Arminia Bielefeld",
	"Inter": "Inter",
	"Hertha BSC": "Hertha Berlin",
	"Stuttgart": "Stuttgart",
	"Köln": "FC Koln",
	"Bayer Leverkusen": "Leverkusen",
	"Freiburg": "Freiburg",
	"Bologna": "Bologna",
}
