package betfair

var teams = map[string]string{
	"West Ham United": "West Ham",
	"Tottenham Hotspur": "Tottenham",
	"Liverpool": "Liverpool",
	"Manchester City": "Man City",
	"West Bromwich Albion": "West Brom",
	"Fulham": "Fulham",
	"Everton": "Everton",
	"Manchester United": "Man Utd",
	"Aston Villa": "Aston Villa",
	"Chelsea": "Chelsea",
	"Arsenal": "Arsenal",
	"Newcastle United": "Newcastle",
	"Sheffield United": "Sheff Utd",
	"Burnley": "Burnley",
	"Wolverhampton Wanders": "Wolves",
	"Roma": "Roma",
	"Leicester City": "Leicester",
	"Lazio": "Lazio",
	"Crystal Palace": "Crystal Palace",
	"Southampton": "Southampton",
	"Schalke 04": "Schalke",
	"Borussia Dortmund": "Dortmund",
	"Leeds United": "Leeds",
	"Brighton & Hove Albion": "Brighton",
	"Werder Bremen": "Werder Bremen",
	"Crotone": "Crotone",
	"Augsburg": "Augsburg",
	"Genoa": "Genoa",
	"Fiorentina": "Fiorentina",
	"Milan": "AC Milan",
	"RB Leipzig": "RB Leipzig",
	"Spezia": "Spezia",
	"Udinese": "Udinese",
	"Eintracht Frankfurt": "Eintracht Frankfurt",
	"Parma": "Parma",
	"Bayern München": "Bayern Munich",
	"Wolfsburg": "Wolfsburg",
	"Sampdoria": "Sampdoria",
	"Benevento": "Benevento",
	"Cagliari": "Cagliari",
	"Napoli": "Napoli",
	"Torino": "Torino",
	"Juventus": "Juventus",
	"Borussia M'gladbach": "Mgladbach",
	"Atalanta": "Atalanta",
	"Mainz 05": "Mainz",
	"Union Berlin": "Union Berlin",
	"Hellas Verona": "Verona",
	"Sassuolo": "Sassuolo",
	"Hoffenheim": "Hoffenheim",
	"Arminia Bielefeld": "Arminia Bielefeld",
	"Inter": "Inter",
	"Hertha BSC": "Hertha Berlin",
	"Stuttgart": "Stuttgart",
	"Köln": "FC Koln",
	"Bayer Leverkusen": "Leverkusen",
	"Freiburg": "Freiburg",
	"Bologna": "Bologna",
	"Lens": "Lens",
	"Nantes": "Nantes",
	"Nîmes": "Nimes",
	"Reims": "Reims",
	"Paris Saint Germain": "Paris Saint Germain",
	"Saint-Étienne": "St Etienne",
	"Montpellier": "Montpellier",
	"Lille": "Lille",
	"Dijon": "Dijon",
	"Nice": "Nice",
	"Strasbourg": "Strasbourg",
	"Monaco": "Monaco",
	"Brest": "Brest",
	"Rennes": "Rennes",
	"Lorient": "Lorient",
	"Olympique Lyonnais": "Lyon",
	"Bordeaux": "Bordeaux",
	"Olympique Marseille": "Marseille",
	"Angers SCO": "Angers",
	"Metz": "Metz",
	"Famalicão": "Famalicao",
	"Santa Clara": "Santa Clara",
	"Benfica": "Benfica",
	"Vitória SC": "Guimaraes",
	"Moreirense": "Moreirense",
	"Gil Vicente": "Gil Vicente",
	"Tondela": "Tondela",
	"Sporting CP": "Sporting Lisbon",
	"Nacional": "Nacional",
	"Belenenses": "Belenenses",
	"Marítimo": "Maritimo",
	"Sporting Braga": "Braga",
	"Paços de Ferreira": "Ferreira",
	"Porto": "FC Porto",
	"Rio Ave": "Rio Ave",
	"Portimonense": "Portimonense",
	"Boavista": "Boavista",
	"Farense": "Farense",
}
