package betfair

var teams = map[string]string{
	"West Ham United": "West Ham",
	"Tottenham Hotspur": "Tottenham",
	"Liverpool": "Liverpool",
	"Manchester City": "Man City",
	"West Bromwich Albion": "West Brom",
	"Fulham": "Fulham",
	"Everton": "Everton",
	"Manchester United": "Man Utd",
	"Aston Villa": "Aston Villa",
	"Chelsea": "Chelsea",
	"Arsenal": "Arsenal",
	"Newcastle United": "Newcastle",
	"Sheffield United": "Sheff Utd",
	"Burnley": "Burnley",
	"Wolverhampton Wanders": "Wolves",
	"Roma": "Roma",
	"Leicester City": "Leicester",
	"Lazio": "Lazio",
	"Crystal Palace": "Crystal Palace",
	"Southampton": "Southampton",
	"Schalke 04": "Schalke",
	"Borussia Dortmund": "Dortmund",
	"Leeds United": "Leeds",
	"Brighton & Hove Albion": "Brighton",
	"Werder Bremen": "Werder Bremen",
	"Crotone": "Crotone",
	"Augsburg": "Augsburg",
	"Genoa": "Genoa",
	"Fiorentina": "Fiorentina",
	"Milan": "AC Milan",
	"RB Leipzig": "RB Leipzig",
	"Spezia": "Spezia",
	"Udinese": "Udinese",
	"Eintracht Frankfurt": "Eintracht Frankfurt",
	"Parma": "Parma",
	"Bayern München": "Bayern Munich",
	"Wolfsburg": "Wolfsburg",
	"Sampdoria": "Sampdoria",
	"Benevento": "Benevento",
	"Cagliari": "Cagliari",
	"Napoli": "Napoli",
	"Torino": "Torino",
	"Juventus": "Juventus",
	"Borussia M'gladbach": "Mgladbach",
	"Atalanta": "Atalanta",
	"Mainz 05": "Mainz",
	"Union Berlin": "Union Berlin",
	"Hellas Verona": "Verona",
	"Sassuolo": "Sassuolo",
	"Hoffenheim": "Hoffenheim",
	"Arminia Bielefeld": "Arminia Bielefeld",
	"Inter": "Inter",
	"Hertha BSC": "Hertha Berlin",
	"Stuttgart": "Stuttgart",
	"Köln": "FC Koln",
	"Bayer Leverkusen": "Leverkusen",
	"Freiburg": "Freiburg",
	"Bologna": "Bologna",
	"Lens": "Lens",
	"Nantes": "Nantes",
	"Nîmes": "Nimes",
	"Reims": "Reims",
	"Paris Saint Germain": "Paris Saint Germain",
	"Saint-Étienne": "St Etienne",
	"Montpellier": "Montpellier",
	"Lille": "Lille",
	"Dijon": "Dijon",
	"Nice": "Nice",
	"Strasbourg": "Strasbourg",
	"Monaco": "Monaco",
	"Brest": "Brest",
	"Rennes": "Rennes",
	"Lorient": "Lorient",
	"Olympique Lyonnais": "Lyon",
	"Bordeaux": "Bordeaux",
	"Olympique Marseille": "Marseille",
	"Angers SCO": "Angers",
	"Metz": "Metz",
	"Famalicão": "Famalicao",
	"Santa Clara": "Santa Clara",
	"Benfica": "Benfica",
	"Vitória SC": "Guimaraes",
	"Moreirense": "Moreirense",
	"Gil Vicente": "Gil Vicente",
	"Tondela": "Tondela",
	"Sporting CP": "Sporting Lisbon",
	"Nacional": "Nacional",
	"Belenenses": "Belenenses",
	"Marítimo": "Maritimo",
	"Sporting Braga": "Braga",
	"Paços de Ferreira": "Ferreira",
	"Porto": "FC Porto",
	"Rio Ave": "Rio Ave",
	"Portimonense": "Portimonense",
	"Boavista": "Boavista",
	"Farense": "Farense",
	"Elche": "Elche",
	"Real Betis": "Betis",
	"Villarreal": "Villarreal",
	"Granada": "Granada",
	"Cádiz": "Cadiz",
	"Osasuna": "Osasuna",
	"Getafe": "Getafe",
	"Real Madrid": "Real Madrid",
	"Levante": "Levante",
	"Real Sociedad": "Real Sociedad",
	"SD Eibar": "Eibar",
	"Huesca": "Huesca",
	"Athletic Club": "Athletic Bilbao",
	"Barcelona": "Barcelona",
	"Sevilla": "Sevilla",
	"Celta de Vigo": "Celta Vigo",
	"Valencia": "Valencia",
	"Atlético Madrid": "Atletico Madrid",
	"Deportivo Alavés": "Alaves",
	"Real Valladolid": "Valladolid",
	"Sparta Rotterdam": "Sparta Rotterdam",
	"Heracles": "Heracles",
	"Willem II": "Willem II",
	"Vitesse": "Vitesse Arnhem",
	"FC Utrecht": "Utrecht",
	"FC Groningen": "FC Groningen",
	"Ajax": "Ajax",
	"PEC Zwolle": "PEC Zwolle",
	"FC Emmen": "Emmen",
	"Feyenoord": "Feyenoord",
	"FC Twente": "FC Twente",
	"SC Heerenveen": "Heerenveen",
	"AZ Alkmaar": "Az Alkmaar",
	"VVV-Venlo": "VVV Venlo",
	"PSV": "PSV",
	"ADO Den Haag": "ADO Den Haag",
	"Fortuna Sittard": "Fortuna Sittard",
	"RKC Waalwijk": "RKC Waalwijk",
	"Varberg BoIS": "Varbergs BolS",
	"Örebro": "Orebro",
	"Mjällby": "Mjallby",
	"Djurgården": "Djurgarden",
	"AIK": "AIK",
	"IFK Göteborg": "IFK Goteborg",
	"Sirius": "IK Sirius",
	"Östersunds FK": "Ostersunds FK",
	"Helsingborg": "Helsingborgs IF",
	"Falkenberg": "Falkenbergs FF",
	"Kalmar": "Kalmar",
	"Malmö FF": "Malmo",
	"Häcken": "BK HACKEN",
	"Elfsborg": "Elfsborg",
	"Norrköping": "IFK Norrkoping",
	"Hammarby": "Hammarby IF",
	"Grimsby Town": "Grimsby",
	"Cambridge United": "Cambridge Utd",
	"Tranmere Rovers": "Tranmere",
	"Crawley Town": "Crawley Town",
	"Salford City": "Salford City",
	"Stevenage": "Stevenage",
	"Newport County": "Newport County",
	"Barrow": "Barrow",
	"Cheltenham Town": "Cheltenham",
	"Carlisle United": "Carlisle",
	"Morecambe": "Morecambe",
	"Exeter City": "Exeter",
	"Colchester United": "Colchester",
	"Mansfield Town": "Mansfield",
	"Southend United": "Southend",
	"Walsall": "Walsall",
	"Harrogate Town": "Harrogate Town",
	"Forest Green Rovers": "Forest Green",
	"Leyton Orient": "Leyton Orient",
	"Bolton Wanderers": "Bolton",
	"Bradford City": "Bradford",
	"Oldham Athletic": "Oldham",
	"Port Vale": "Port Vale",
	"Scunthorpe United": "Scunthorpe",
	"Shrewsbury Town": "Shrewsbury",
	"Oxford United": "Oxford Utd",
	"Charlton Athletic": "Charlton",
	"Fleetwood Town": "Fleetwood Town",
	"Blackpool": "Blackpool",
	"Peterborough United": "Blackpool",
	"Crewe Alexandra": "Crewe",
	"Burton Albion": "Burton Albion",
	"Wigan Athletic": "Wigan",
	"Accrington Stanley": "Accrington",
	"AFC Wimbledon": "AFC Wimbledon",
	"Hull City": "Hull",
	"Bristol Rovers": "Bristol Rovers",
	"Ipswich Town": "Ipswich",
	"Sunderland": "Sunderland",
	"Swindon Town": "Swindon",
	"Portsmouth": "Portsmouth",
	"Rochdale": "Rochdale",
	"Northampton Town": "Northampton",
	"Gillingham": "Gillingham",
	"Doncaster Rovers": "Doncaster",
	"Plymouth Argyle": "Plymouth",
	"Lincoln City": "Lincoln",
	"Milton Keynes Dons": "MK Dons",
	"Luton Town": "Luton",
	"Derby County": "Derby",
	"Reading": "Reading",
	"AFC Bournemouth": "Bournemouth",
	"Blackburn Rovers": "Blackburn",
	"Barnsley": "Barnsley",
	"Middlesbrough": "Middlesbrough",
	"Brentford": "Brentford",
	"Swansea City": "Swansea",
	"Stoke City": "Stoke",
	"Millwall": "Millwall",
	"Watford": "Watford",
	"Preston North End": "Preston",
	"Wycombe Wanderers": "Wycombe",
	"Norwich City": "Norwich",
	"Bristol City": "Bristol City",
	"Birmingham City": "Birmingham",
	"Coventry City": "Coventry",
	"Huddersfield Town": "Huddersfield",
	"Nottingham Forest": "Nottm Forest",
	"Queens Park Rangers": "QPR",
	"Rotherham United": "Rotherham",
	"Cardiff City": "Cardiff",
	"Sheffield Wednesday": "Sheff Wed",
	"OH Leuven": "Oud-Heverlee Leuven",
	"Kortrijk": "Kortrijk",
	"Sporting Charleroi": "Charleroi",
	"Club Brugge": "Club Brugge",
	"Antwerp": "Antwerp",
	"Standard Liège": "Standard",
	"KV Oostende": "KV Oostende",
	"AS Eupen": "Eupen",
	"Waasland-Beveren": "Waasland-Beveren",
	"Zulte-Waregem": "Zulte-Waregem",
	"Sint-Truiden": "Sint Truiden",
	"Anderlecht": "Anderlecht",
	"Gent": "Gent",
	"Genk": "Genk",
	"Cercle Brugge": "Cercle Brugge",
	"Mechelen": "Yellow-Red Mechelen",
	"Beerschot-Wilrijk": "Kfco Beerschot Wilrijk",
	"Royal Excel Mouscron": "Royal Mouscron-peruwelz",
}
